name: Auto Commit Daily Update

on:
  schedule:
    - cron: '0 1/4 * * *' # Manual crontab.guru

jobs:
  auto_commit_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
      - name: Modify file
        run: |
          DATE=$(date +%Y-%m-%d_%H-%M-%S)
          echo "Last updated: $DATE" > update.txt
          echo "This file was automatically updated at $DATE" >> update.txt

      - name: Auto commit changes
        run: |
          git config user.email "rama4zis@proton.me" 
          git config user.name "rama4zis"
          git add .
          git commit -m "💖" || echo "No changes to commit"
          git push
